version: '2.1'
orbs:
  composer: stockfiller/composer@2
  php-coveralls: nekman/php-coveralls@1
  phpunit: stockfiller/phpunit@1
workflows:
  foo:
    jobs:
      - php-coveralls/generate_upload:
          clover-path: coverage/clover.xml
          executor: php
          generate-steps:
            - phpunit/test:
                coverage: clover
                coverage-path: coverage/clover.xml
                src-path: src
                test-path: tests
          pre-steps:
            - run:
                command: |-
                  apk add --update --no-cache ${PHPIZE_DEPS}
                  pecl install pcov-1.0.6
                  docker-php-ext-enable pcov
                name: Install PCOV
            - composer/install_bin
